# Generated by Django 5.2.17 on 2026-08-18 15:24

import django.core.validators
import django.db.models.deletion
import genealogy.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BurialPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, db_index=True, max_length=150)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('address', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='burialplace_lat_lon_both_or_neither')],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('patronymic', models.CharField(blank=True, max_length=150)),
                ('maiden_name', models.CharField(blank=True, max_length=150)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_date_text', models.CharField(blank=True, max_length=255)),
                ('birth_place', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('alive', 'Alive'), ('deceased', 'Deceased')], max_length=10)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('death_date_text', models.CharField(blank=True, max_length=255)),
                ('burial_plot_details', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/', validators=[genealogy.validators.validate_image_max_size])),
                ('grave_photo', models.ImageField(blank=True, null=True, upload_to='grave_photos/%Y/%m/', validators=[genealogy.validators.validate_image_max_size])),
                ('extra_info', models.JSONField(blank=True, default=list, validators=[genealogy.validators.validate_extra_info])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('burial_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='genealogy.burialplace')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_persons', to=settings.AUTH_USER_MODEL)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_father', to='genealogy.person')),
                ('linked_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL)),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_mother', to='genealogy.person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_persons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_start_text', models.CharField(blank=True, max_length=255)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('date_end_text', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, choices=[('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('partnership', 'Partnership')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unions_as_person1', to='genealogy.person')),
                ('person2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unions_as_person2', to='genealogy.person')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('person1', models.F('person2')), _negated=True), name='union_no_self_marriage')],
            },
        ),
    ]
