# Generated by Django 5.2.17 on 2026-08-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='burialplace',
            options={'ordering': ['city', 'name']},
        ),
    ]
